# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CSV_Combiner"
version = "1.0.0"
readme = "README.MD"
dependencies = [
    "numpy",
    "pandas"
]
requires-python = ">=3.6"

